### ISSUE TITLE
Making it Work Locally

### ISSUE THREAD

**Issue by sriks6711** [MunnazzahAslam/FaceDetection#1]
Thank you for this, Aslam.

I downloaded the code and I ran into a strange problem.

When I run it locally as in http://localhost:8383/FaceDetection/index.html, the page is blank.

But when I host and run it on Surge.sh as in https://gabby-coat.surge.sh/, it is working.

It turned out that the port number was causing a problem when I looked into the console.

So, if one changes  [faceapi.nets.tinyFaceDetector.loadFromUri("models")] to [[ faceapi.nets.tinyFaceDetector.loadFromUri("./models")]] (notice the dot before models), it was running.

Hope this is useful to you and others. Thank you once again.

**Comment by MunnazzahAslam** [comment]
Hey, thank you for solving the issue!
